# Generated by Django 4.1.5 on 2023-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidop', models.CharField(max_length=50)),
                ('apellidom', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
